name: caliweather
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  parse_server_sdk_flutter: ^3.1.3
  flutter_map: ^3.1.0
  sqflite:
  path:
  geolocator: ^9.0.2
  path_provider: ^2.0.12
  flutter_native_splash: ^2.2.17
  weather: ^2.0.1
  fl_chart: ^0.61.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  weather_icons: ^3.0.0-nullsafety.x
  shared_preferences: ^2.0.17
  persistent_bottom_nav_bar: any
  smooth_page_indicator: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/  

flutter_native_splash:
  image: assets/splash.png
  color: "FFFFFF"
