name: caliweather
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  fl_chart: ^0.61.0
  flash: ^2.0.5
  flutter_map: ^3.1.0
  flutter_map_tile_caching: ^7.2.0
  flutter_native_splash: ^2.2.17
  flutter_speed_dial: ^6.2.0
  geolocator: ^9.0.2
  http: ^0.13.5
  intl: ^0.18.0
  isar_flutter_libs: ^3.0.5
  path:
  persistent_bottom_nav_bar: any
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.17
  smooth_page_indicator: ^1.0.1
  sqflite:
  weather: ^2.0.1
  weather_icons: ^3.0.0-nullsafety.x
  

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  assets:
    - assets/  

flutter_native_splash:
  image: assets/splash.png
  color: "FFFFFF"
